### ISSUE TITLE
set packages to broken

### ISSUE THREAD

**Issue by looooo** [conda-forge/netgen-feedstock#16]
@conda-forge/core 
please set all __netgen-6.2.1811.b0-py36*__ to broken:
https://anaconda.org/conda-forge/netgen/files

![bildschirmfoto von 2019-01-15 15-09-46](https://user-images.githubusercontent.com/5084704/51185559-c3970380-18d7-11e9-967c-4a5650a8fbb2.png)

**Comment by jjhelmus** [comment]
@looooo Done, can you verify that the packages have the correct label now?  
https://anaconda.org/conda-forge/netgen/files

**Comment by looooo** [comment]
looks good. thanks

**Comment by looooo** [comment]
@conda-forge/core

Please set also these packages to broken:
__all__ packages with __version 6.2.1811.b0__

![bildschirmfoto von 2019-01-25 11-03-53](https://user-images.githubusercontent.com/5084704/51739103-f89e1580-2090-11e9-9dec-18441ec049a7.png)

thanks

**Comment by ocefpaf** [comment]
Done. Can you check?

https://anaconda.org/conda-forge/netgen/files?version=6.2.1811.b0

**Comment by looooo** [comment]
thanks.
