### ISSUE TITLE
Reminder 6.2.1802-pyxy_2 freecad issues

### ISSUE THREAD

**Issue by looooo** [conda-forge/netgen-feedstock#5]
this build has issues with freecad. I guess it is caused by the added patch. I will change this once smesh is able to build on osx.

**Comment by looooo** [comment]
@conda-forge/core sry again there is the need to disable some builds:

all 6.2.1802-py<xy>_2 and 6.2.1802-py<xy>_1
which are these checked builds.
![grafik](https://user-images.githubusercontent.com/5084704/39097496-39cdbbb4-465d-11e8-8801-e1649b85ded6.png)

thanks

**Comment by ocefpaf** [comment]
Just did that. Can you check if I got the right ones?

**Comment by looooo** [comment]
perfect, thanks
